# Generated by Django 6.0.1 on 2026-02-01 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='care_guide',
        ),
        migrations.AddField(
            model_name='plant',
            name='care_difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Difficulty level of caring for this plant', max_length=20),
        ),
        migrations.AddField(
            model_name='plant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation timestamp'),
        ),
        migrations.AddField(
            model_name='plant',
            name='fertilizer_schedule',
            field=models.CharField(blank=True, help_text='Fertilizer application schedule', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='humidity_level',
            field=models.CharField(blank=True, help_text='Preferred humidity level', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='light_requirements',
            field=models.CharField(blank=True, help_text='Light conditions needed', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='propagation_methods',
            field=models.TextField(blank=True, help_text='How to propagate the plant', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='pruning_info',
            field=models.TextField(blank=True, help_text='Pruning instructions', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='soil_type',
            field=models.CharField(blank=True, help_text='Recommended soil type', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='temperature_range',
            field=models.CharField(blank=True, help_text='Optimal temperature range', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AddField(
            model_name='plant',
            name='watering_frequency',
            field=models.CharField(blank=True, help_text='How often to water the plant', max_length=100, null=True),
        ),
    ]
