# Generated by Django 6.0.1 on 2026-02-02 21:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_remove_plant_care_guide_plant_care_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='image',
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plant_images/')),
                ('caption', models.CharField(blank=True, help_text='Caption for the image', max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary image for the plant')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the image was added')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plants.plant')),
            ],
        ),
    ]
