# Generated by Django 6.0.1 on 2026-02-02 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_remove_plant_image_plantimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantimage',
            options={'ordering': ['-is_primary', 'created_at']},
        ),
    ]
