# Generated by Django 6.0.4 on 2026-04-22 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_plantimage_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='description_en',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='english_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='propagation_methods_en',
            field=models.TextField(blank=True, help_text='How to propagate the plant', null=True),
        ),
    ]
