# Generated by Django 6.0.4 on 2026-04-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_plant_description_en_plant_english_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='english_name',
            field=models.CharField(help_text='English Name', max_length=255, unique=False, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='farsi_name',
            field=models.CharField(help_text='Farsi Name', max_length=255),
        ),
    ]
