# Generated by Django 6.0.4 on 2026-04-22 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_alter_plant_english_name_alter_plant_farsi_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='english_name',
            new_name='name_en',
        ),
    ]
