# Generated by Django 6.0.4 on 2026-04-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_rename_english_name_plant_name_en'),
    ]

    operations = [
    ]
