# Generated by Django 6.0.4 on 2026-04-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_drop_unique_english_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='name_en',
            new_name='english_name',
        ),
    ]
