# Generated by Django 6.0.4 on 2026-04-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0011_alter_plant_english_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='english_name',
            field=models.CharField(blank=True, help_text='English Name', max_length=255, null=True),
        ),
    ]
