# Generated by Django 6.0.4 on 2026-05-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0012_alter_plant_english_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='fertilizer_schedule_en',
            field=models.CharField(blank=True, help_text='Fertilizer application schedule (English)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='garden_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of users who added this plant to their garden'),
        ),
        migrations.AddField(
            model_name='plant',
            name='humidity_level_en',
            field=models.CharField(blank=True, help_text='Preferred humidity level (English)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='light_requirements_en',
            field=models.CharField(blank=True, help_text='Light conditions needed (English)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='pruning_info_en',
            field=models.TextField(blank=True, help_text='Pruning instructions (English)', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='soil_type_en',
            field=models.CharField(blank=True, help_text='Recommended soil type (English)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='temperature_range_en',
            field=models.CharField(blank=True, help_text='Optimal temperature range (English)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the plant detail has been viewed'),
        ),
        migrations.AddField(
            model_name='plant',
            name='watering_frequency_en',
            field=models.CharField(blank=True, help_text='How often to water the plant (English)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(help_text='Description in Persian'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description_en',
            field=models.TextField(help_text='Description in English'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='fertilizer_schedule',
            field=models.CharField(blank=True, help_text='Fertilizer application schedule (Persian)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='humidity_level',
            field=models.CharField(blank=True, help_text='Preferred humidity level (Persian)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='light_requirements',
            field=models.CharField(blank=True, help_text='Light conditions needed (Persian)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='propagation_methods',
            field=models.TextField(blank=True, help_text='How to propagate the plant (Persian)', null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='propagation_methods_en',
            field=models.TextField(blank=True, help_text='How to propagate the plant (English)', null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='pruning_info',
            field=models.TextField(blank=True, help_text='Pruning instructions (Persian)', null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='soil_type',
            field=models.CharField(blank=True, help_text='Recommended soil type (Persian)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='temperature_range',
            field=models.CharField(blank=True, help_text='Optimal temperature range (Persian)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='watering_frequency',
            field=models.CharField(blank=True, help_text='How often to water the plant (Persian)', max_length=100, null=True),
        ),
    ]
