# Generated by Django 6.0.4 on 2026-06-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0014_plant_comment_count_plant_favourite_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='other_names',
            field=models.CharField(blank=True, help_text='Other Persian names', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='other_names_en',
            field=models.CharField(blank=True, help_text='Other English names', max_length=255, null=True),
        ),
    ]
