# Generated by Django 6.0.1 on 2026-02-01 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation timestamp'),
        ),
        migrations.AddField(
            model_name='disease',
            name='prevention_methods',
            field=models.TextField(blank=True, help_text='Methods to prevent the disease', null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='severity_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Severity level of the disease', max_length=20),
        ),
        migrations.AddField(
            model_name='disease',
            name='spread_rate',
            field=models.CharField(choices=[('slow', 'Slow'), ('moderate', 'Moderate'), ('fast', 'Fast')], default='moderate', help_text='How fast the disease spreads', max_length=50),
        ),
        migrations.AddField(
            model_name='disease',
            name='treatment_duration',
            field=models.CharField(blank=True, help_text='Expected duration for treatment', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
    ]
