# Generated by Django 6.0.4 on 2026-05-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_disease_created_at_disease_prevention_methods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='description_fa',
            field=models.TextField(blank=True, help_text='Description in Persian', null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='name_fa',
            field=models.CharField(blank=True, help_text='Disease name in Persian', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='prevention_methods_fa',
            field=models.TextField(blank=True, help_text='Prevention methods in Persian', null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='solution_fa',
            field=models.TextField(blank=True, help_text='Treatment solution in Persian', null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms_fa',
            field=models.TextField(blank=True, help_text='Symptoms in Persian', null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times disease detail has been viewed'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(help_text='Description in English'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(help_text='Disease name in English', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='prevention_methods',
            field=models.TextField(blank=True, help_text='Prevention methods in English', null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='solution',
            field=models.TextField(help_text='Treatment solution in English'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(help_text='Symptoms in English'),
        ),
    ]
