# Generated by Django 6.0.4 on 2026-05-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0004_disease_comment_count_diseasecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='affected_plants',
        ),
        migrations.AddField(
            model_name='disease',
            name='affected_plants_list',
            field=models.TextField(blank=True, help_text="Comma-separated list of affected plant names (e.g., 'Rose, Cucumber, Strawberry')", null=True),
        ),
    ]
