# Generated by Django 6.0.4 on 2026-05-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0005_remove_disease_affected_plants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='is_infectious_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
