# Generated by Django 6.0.4 on 2026-07-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0006_disease_is_infectious_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='image',
            field=models.ImageField(blank=True, help_text='Disease image', null=True, upload_to='diseases/'),
        ),
    ]
