# Generated by Django 6.0.4 on 2026-07-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0007_disease_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='image_url',
            field=models.URLField(blank=True, help_text='Disease image URL', max_length=500, null=True),
        ),
    ]
