# Generated by Django 6.0.1 on 2026-02-01 07:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='fertilizing_interval_days',
            field=models.IntegerField(default=30, help_text='Number of days between fertilizing'),
        ),
        migrations.AddField(
            model_name='userplant',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('needs_attention', 'Needs Attention'), ('unhealthy', 'Unhealthy')], default='healthy', help_text='Current health status of the plant', max_length=20),
        ),
        migrations.AddField(
            model_name='userplant',
            name='last_fertilized',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the plant was last fertilized'),
        ),
        migrations.AddField(
            model_name='userplant',
            name='last_pruned',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the plant was last pruned'),
        ),
        migrations.AddField(
            model_name='userplant',
            name='last_watered',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the plant was last watered'),
        ),
        migrations.AddField(
            model_name='userplant',
            name='next_fertilizing_date',
            field=models.DateTimeField(blank=True, help_text='Date when the plant needs to be fertilized next', null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='next_pruning_date',
            field=models.DateTimeField(blank=True, help_text='Date when the plant needs to be pruned next', null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='next_watering_date',
            field=models.DateTimeField(blank=True, help_text='Date when the plant needs to be watered next', null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='notes',
            field=models.TextField(blank=True, help_text='Personal notes about the plant', null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='pruning_interval_days',
            field=models.IntegerField(default=90, help_text='Number of days between pruning'),
        ),
        migrations.AddField(
            model_name='userplant',
            name='watering_interval_days',
            field=models.IntegerField(default=7, help_text='Number of days between watering'),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('care_type', models.CharField(choices=[('watering', 'Watering'), ('fertilizing', 'Fertilizing'), ('pruning', 'Pruning'), ('pest_control', 'Pest Control'), ('repotting', 'Repotting'), ('other', 'Other')], default='watering', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_interval', models.IntegerField(blank=True, help_text='Interval in days for recurring reminders', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
                ('user_plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='gardens.userplant')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
