# Generated by Django 6.0.4 on 2026-05-11 20:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0004_reminder_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='pot_size',
            field=models.CharField(choices=[('no_pot', 'بدون گلدان'), ('small', 'گلدان کوچک'), ('medium', 'گلدان متوسط'), ('large', 'گلدان بزرگ'), ('extra_large', 'گلدان خیلی بزرگ')], default='medium', help_text='سایز گلدان فعلی گیاه', max_length=20),
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='ارتفاع گیاه (مثلاً 15.5)', max_digits=6, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='عرض یا پهنای گیاه', max_digits=6, null=True)),
                ('unit', models.CharField(choices=[('cm', 'سانتی\u200cمتر'), ('inch', 'اینچ')], default='cm', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='یادداشت مرتبط با این رکورد رشد', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='gardens.userplant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
