# Generated by Django 6.0.4 on 2026-05-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0005_userplant_pot_size_growthrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='last_fertilized',
            field=models.DateTimeField(blank=True, default=None, help_text='Date when the plant was last fertilized', null=True),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='last_pruned',
            field=models.DateTimeField(blank=True, default=None, help_text='Date when the plant was last pruned', null=True),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='last_watered',
            field=models.DateTimeField(blank=True, default=None, help_text='Date when the plant was last watered', null=True),
        ),
    ]
