# Generated by Django 6.0.4 on 2026-05-13 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0006_alter_userplant_last_fertilized_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام کاربر')),
                ('response', models.TextField(verbose_name='پاسخ دستیار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_chats', to=settings.AUTH_USER_MODEL)),
                ('user_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='gardens.userplant')),
            ],
            options={
                'verbose_name': 'پیام چت گیاه',
                'verbose_name_plural': 'پیام\u200cهای چت گیاهان',
                'ordering': ['-created_at'],
            },
        ),
    ]
