# Generated by Django 6.0.4 on 2026-06-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0007_plantchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
